<?php
/** @var $block \OH\Bestsellers\Block\Bestsellers */

$prodColl = $block->getBestsellerProduct();
$addedIds = [];
$showTitle = $block->getShowTitleBestsellers();

if ($exist = ($prodColl && $prodColl->count())) {
    $mode = 'grid';
    $title = $block->getTitleBestsellers();
    $type = 'widget-bestseller-grid';
    $image = 'oh_bestseller_products_widget_grid';
    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $_helper = $this->helper(Magento\Catalog\Helper\Output::class);
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
}
?>

<?php if ($exist): ?>
    <div class="block block-bestseller-products <?php echo $mode; ?>">
        <?php if ($showTitle): ?>
            <div class="block-title">
                <strong role="heading" aria-level="2"><?php echo $title; ?></strong>
            </div>
        <?php endif; ?>
        <div class="block-content">
            <div class="products-<?= $mode ?> <?= $mode ?>">
                <ol class="product-items <?= $type ?>">
                    <?php foreach ($prodColl as $_item) : ?>
                        <?php $product = $block->getProduct($_item->getProductId()) ?>
                        <?php if (count($addedIds) >= $block->getProductLimit()): break;endif; ?>
                        <?php if (!$block->isVisible($product) || in_array($product->getEntityId(), $addedIds) || in_array($product->getParentId(), $addedIds)): continue;endif; ?>
                        <?php $addedIds[] = $product->getEntityId(); ?>
                        <li class="product-item">
                            <div class="product-item-info">
                                <a href="<?= $block->escapeUrl($block->getProductUrl($product)) ?>"
                                   class="product-item-photo">
                                    <?= $block->getImage($product, $image)->toHtml() ?>
                                </a>
                                <div class="product-item-details">
                                    <strong class="product-item-name">
                                        <a title="<?= $block->escapeHtmlAttr($product->getName()) ?>"
                                           href="<?= $block->escapeUrl($block->getProductUrl($product)) ?>"
                                           class="product-item-link">
                                            <?= $block->escapeHtml($product->getName()) ?>
                                        </a>
                                    </strong>
                                    <?php if ($templateType) : ?>
                                        <?= $block->getReviewsSummaryHtml($product, $templateType) ?>
                                    <?php endif; ?>
                                    <?= $block->getProductPriceHtml($product, $type) ?>

                                    <?php if ($showWishlist || $showCompare || $showCart) : ?>
                                        <div class="product-item-actions">
                                            <?php if ($showCart) : ?>
                                                <div class="actions-primary">
                                                    <?php if ($product->isSaleable()) : ?>
                                                        <?php if (!$product->getTypeInstance()->isPossibleBuyFromList($product)
                                                        ) : ?>
                                                            <button class="action tocart primary"
                                                                    data-mage-init='{"redirectUrl":{"url":"<?= $block->escapeUrl($block->getAddToCartUrl($product)) ?>"}}'
                                                                    type="button"
                                                                    title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                            </button>
                                                        <?php else : ?>
                                                            <?php
                                                            $postDataHelper = $this->helper(Magento\Framework\Data\Helper\PostHelper::class);
                                                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($product), ['product' => $product->getEntityId()])
                                                            ?>
                                                            <button class="action tocart primary"
                                                                    data-post='<?= /* @noEscape */
                                                                    $postData ?>'
                                                                    type="button" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>">
                                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                            </button>
                                                        <?php endif; ?>
                                                    <?php else : ?>
                                                        <?php if ($product->isAvailable()) : ?>
                                                            <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                                        <?php else : ?>
                                                            <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                            <?php if ($showWishlist || $showCompare) : ?>
                                                <div class="actions-secondary" data-role="add-to-links">
                                                    <?php if ($this->helper(Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist) : ?>
                                                        <a href="#"
                                                           data-post='<?= /* @noEscape */
                                                           $block->getAddToWishlistParams($_item) ?>'
                                                           class="action towishlist" data-action="add-to-wishlist"
                                                           title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                            <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                    <?php if ($block->getAddToCompareUrl() && $showCompare) : ?>
                                                        <?php $compareHelper = $this->helper(Magento\Catalog\Helper\Product\Compare::class); ?>
                                                        <a href="#" class="action tocompare"
                                                           title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>"
                                                           data-post='<?= /* @noEscape */
                                                           $compareHelper->getPostDataParams($_item) ?>'>
                                                            <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </li>
                    <?php endforeach ?>
                </ol>
            </div>
        </div>
    </div>
<?php endif; ?>
